# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf6a0fb60a2c48d30340b698b3d83eb3722c94768f9d5c1c160757681c634cac26609e916aafac837fae3ac99bad059d0cda898d5cf6fe135f1ebba88df53a53

test:
  secret_key_base: 0380299de20be6c084069ebd932fc1c734e3b89a2f075f140367b06422ea8d16e31ff7650016133a563bf3648cedf303f4562b361426f83d59130a61dbd970bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
